default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shop_backend_development
  username: joshseckman
  password: Michigan1
  port: 5432
  host: localhost

test:
  <<: *default
  database: shop_backend_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
